package com.parkcharge2.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PARK_REC".
 */
public class ParkRec {

    private Long id;
    private String carNo;
    private Integer carType;
    private java.util.Date createTime;

    public ParkRec() {
    }

    public ParkRec(Long id) {
        this.id = id;
    }

    public ParkRec(Long id, String carNo, Integer carType, java.util.Date createTime) {
        this.id = id;
        this.carNo = carNo;
        this.carType = carType;
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCarNo() {
        return carNo;
    }

    public void setCarNo(String carNo) {
        this.carNo = carNo;
    }

    public Integer getCarType() {
        return carType;
    }

    public void setCarType(Integer carType) {
        this.carType = carType;
    }

    public java.util.Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

}
