package com.parkcharge2.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.parkcharge2.entity.ParkRec;

import com.parkcharge2.dao.ParkRecDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig parkRecDaoConfig;

    private final ParkRecDao parkRecDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        parkRecDaoConfig = daoConfigMap.get(ParkRecDao.class).clone();
        parkRecDaoConfig.initIdentityScope(type);

        parkRecDao = new ParkRecDao(parkRecDaoConfig, this);

        registerDao(ParkRec.class, parkRecDao);
    }
    
    public void clear() {
        parkRecDaoConfig.getIdentityScope().clear();
    }

    public ParkRecDao getParkRecDao() {
        return parkRecDao;
    }

}
